# Generated by Django 5.0.1 on 2024-02-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postmodel_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='./book-images/uploads/'),
        ),
    ]
